train:
  root: /home/tw/Desktop/Dev/Dataset/COCO2017/train2017
  annFile: /home/tw/Desktop/Dev/Dataset/COCO2017/annotations_trainval2017/annotations/instances_train2017.json

val:
  root: /home/tw/Desktop/Dev/Dataset/COCO2017/val2017
  annFile: /home/tw/Desktop/Dev/Dataset/COCO2017/annotations_trainval2017/annotations/instances_val2017.json

test:
  root: /home/tw/Desktop/Dev/Dataset/COCO2017/val2017

dataset_stat:
  - [0.485, 0.456, 0.406]   # mean
  - [0.229, 0.224, 0.225]   # std
